name: Build Linux

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
        sudo apt-get install -y gcc g++
        sudo apt-get install -y ccache
    - name: Install library dependencies
      run: |
        sudo apt-get install -y luajit-5.1-2 luajit-5.1-dev
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/ccache
        key: ${{ runner.os }}-release-${{ github.sha }}
        restore-keys: ${{ runner.os }}-release-
    - name: Clone Omen
      uses: actions/checkout@v4
    - name: Configure Omen
      env:
        CC: gcc
        CXX: g++
      run: |
        cmake \
          -S . \
          -B build \
          --preset=linux-release
    - name: Build Omen
      run: ninja -C build
    - name: Save ccache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/ccache
        key: ${{ runner.os }}-release-${{ github.sha }}
