name: build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        compiler:
          - { pkg: g++, exe: 'g++', version: 13 }
          - { pkg: clang, exe: 'clang++', version: 18 }

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.compiler.pkg}}-${{ matrix.compiler.version }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Build Tools
        run: python -m pip install meson ninja
      - name: Build Omen
        env:
          CXX: ${{ matrix.compiler.exe }}-${{ matrix.compiler.version }}
        run: |
          meson setup \
            -Dtests=true \
            -Dpedantic=true \
            --werror \
            --warnlevel=3 \
            build
          meson compile -C build
      - name: Run Tests
        run: meson test -v -C build
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Packages
        run: |
          pip3 install meson ninja
      - name : Build Omen
        run: |
          meson setup `
            -Dtests=true `
            -Dpedantic=true `
            --werror `
            --warnlevel=3 `
            build
          meson compile -C build
      - name: Run Tests
        run: meson test -v -C build
