name: Build Linux

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ ccache
      - name: Restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/ccache
          key: ${{ runner.os }}-release-
      - name: Clone Omen
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure Omen
        run: |
          cmake \
            -S . \
            -B build \
            -DOMEN_TEST=ON \
            --preset=linux-release
      - name: Build Omen
        run: ninja -C build
      - name: Test Omen
        run: build/out/omen_test
      - name: Save ccache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/ccache
          key: ${{ runner.os }}-release-${{ github.sha }}
