name: Build Windows

on:
  [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Install build dependencies
        run: |
          choco install -y ccache ninja
      - name: Get LocalAppData Directory
        run: echo ("LOCALAPPDATA_DIR=" + $env:LOCALAPPDATA) >> $env:GITHUB_ENV
      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.LOCALAPPDATA_DIR }}/ccache
          key: ${{ runner.os }}-release-
      - name: Clone Omen
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure Omen
        run: |
          cmake `
            -S . `
            -B build `
            -DOMEN_TEST=ON `
            -G Ninja `
            --preset=windows-release
      - name: Build Omen
        run: cmake --build build
      - name: Test Omen
        run: build/out/omen_test.exe
      - name: Save ccache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.LOCALAPPDATA_DIR }}/ccache
          key: ${{ runner.os }}-release-${{ github.sha }}
